### ISSUE TITLE
Add way to use from a rich OS

### ISSUE THREAD

**Issue by Jookia** [rhboot/shim#391]
Currently the only way to use the shim is through its console, before the OS has booted.
This is unfortunate for headless setups and people that require assistive technologies to use their computers.
Having a way to view logs, errors messages and manages keys from a rich OS would be very helpful.

**Comment by frozencemetery** [comment]
shim is noninteractive even for users that don't need assistive tech.  I don't know what you mean by "rich OS", or how we would boot to one if there were a shim problem.  Perhaps you're looking for [mokutil](https://github.com/lcp/mokutil)?

**Comment by julian-klode** [comment]
@frozencemetery basically request seems to say that it'd be nice if instead of just logging to console, we'd also dump it into an EFI variable or something more persistent (at least available to runtime at boot), so it can be read inside the normal OS. Right now it's take video and read video to read shim log, which is understandably annoying

**Comment by Jookia** [comment]
No, specifically the issue is that you can't use the interface to configure things from the rich OS. For example, you can't change keys.
