### ISSUE TITLE
shim-signed not working with Macbook Pro 2020

### ISSUE THREAD

**Issue by kami83** [rhboot/shim#457]
Hi, i am trying to run a Macbook Pro (3 Distros, Windows, MacOS, Linux) with refind and i would like to activate shim with Secure Boot. Can anyone tell me why my Macbook always goes to Recovery Boot, when i try to launch shimx64.efi. I tried to use an Ubuntu version with Microsoft-signed. Is here anyone how can help me with this problem?

Thanks  a lot.

BG kami

**Comment by afrodidact** [comment]
Did you find a resolution for this issue?

**Comment by kami83** [comment]
No sorry. Nothing new. It doesnt work.

BR kami

**Comment by frozencemetery** [comment]
Apple's UEFI is also more likely to be divergent than that of other vendors, and I don't believe any shim developers currently own Apple hardware.  Additionally, they don't anchor their root of trust with Microsoft (because they're Apple and sell an OS), so whether you're signed or unsigned I don't think would matter here.

While I understand booting multiple operating systems on the same machine is attractive, using a tool like refind as an additional boot manager introduces a fragile layer of complexity.  When I used to do this on Apple hardware, I was unable to get refind to ever work (I'm not convinced it does, and this is not a place to debug it).  I suggest you install one operating system per drive and either physically swap drives or use Apple's boot manager to switch OSs (hold I think it's the Option key during boot) - that's how I did it (in 2015, on a MacPro4,1).  Having them on the same drive means they'll quite likely step on each other later, be that partition tables or ESP shenanigans.

Finally, you are using a distro's shim, so they may be more helpful than upstream.  Concretely: if you have a generally reasonable setup, I suggest you file a bug with Ubuntu and see if they can help you more.  They'll probably want more information to start with, including how you installed and stuff.

Best of luck to you.
