### ISSUE TITLE
Using OVERRIDE_SECURY_POLICY flag causes build to fail

### ISSUE THREAD

**Issue by bryteise** [rhboot/shim#596]
When running `make OVERRIDE_SECURITY_POLICY=1` the build fails as the security_policy.o isn't getting built with this define set (ends up failing in linking with missing function definitions but there might be other functional issues).

If I add the test and set for `OVERRIDE_SECURITY_POLICY` in the lib's Makefile setting the define it at least builds. Not sure if there are other things that should be set in the lib DEFINES from the top level Makefile DEFINES but at least that one causes problems.

**Comment by dennis-tseng99** [comment]
Would you please modify Make.defaults like this:
![image](https://github.com/rhboot/shim/assets/47710835/b58a90b1-28f9-44b7-9296-930954dfbcb2)

A patch will be committed soon. Thanks for your question.

**Comment by dennis-tseng99** [comment]
After ```export``` OVERRIDE_SECURITY_POLIC, I can successfully make files by using the following command:

```
make clean; make RELEASE=0 SHIMSTEM=shim MMSTEM=MokManager FBSTEM=fbx64 ENABLE_HTTPBOOT=1 OVERRIDE_SECURITY_POLICY=1 DEFAULT_LOADER="\\\\\\\\grub.efi" shim.efi.debug shim.efi MokManager.efi fbx64.efi
```

**Comment by bryteise** [comment]
The above PR is what ended up working for me.

**Comment by dennis-tseng99** [comment]
I've got that. Thanks for your response indeed.

**Comment by mikebeaton** [comment]
I suggested a change to @bryteise's helpful [PR](https://github.com/rhboot/shim/pull/600), but I remain confused about the status of this bug in the first place, and wonder if anyone could clarify?  (cc @dennis-tseng99 @bluca - tyvm in advance for any info)

The inability to build with OVERRIDE_SECURITY_POLICY=1 seems longstanding, but the OVERRIDE_SECURITY_POLICY code itself is also longstanding, and there is at least one useful [new commit](https://github.com/rhboot/shim/commit/1f38cb30a5e1dcea97b8d48915515b866ec13c32) which specifically updates it. What was the supported (unsupported?/undocumented?) way to build this code up to now - and, if I can ask, is it included in most normal/typical shim builds?

**Comment by julian-klode** [comment]
I've read up a bit and got some feedback and I'm inclined to suggest removing the code for OVERRIDE_SECURITY_POLICY. It's an ugly hack that's not part of UEFI, it hasn't built in ages, and we do not consider the impact of changes we make to its functionality.

Certainly the idea of boot loaders loading drivers using shim keys is not something that has ever crossed my mind, and it's not really something we should be enabling.

The valid use cases are starting executable, the LoadImage/StartImage/UnloadImage functions in the BS, and the goal for shim 16 would be to hook those directly.

**Comment by mikebeaton** [comment]
Is it not the case that boot loaders loading drivers using shim keys is required, e.g. for a non-grub post-shim boot loader to load MOK signed kernel modules?

**Comment by kukrimate** [comment]
@mikebeaton MOK signed kernel modules do not use any boot services code to get loaded, those signatures are verified by the kernel itself. The MOK certificates are availables at runtime in the `MokListRT` UEFI variable and then runtime things can do their own verification against those.

I am also very much for revmoving `OVERRIDE_SECURITY_POLICY`, it is an ugly hack based on the implementation details of some firrmwares, and it is definitely not how any bootloaders should use shim. 

Your bootloader should also use the shim protocol like everything else to verify its payload, then use its own loader to load said payload. (A PE loader if it happens to be a PE, or a loader for whatever executable format you want to use).

Getting a shim with an embedded CA with such weirdness signed on the MS UEFI 3rd party CA is of course at the discretion of Microsoft, but nonthless it's not stopping you from using the code.

**Comment by mikebeaton** [comment]
Hi - Thanks for feedback.

MOK certificates are definitely used as additional, allowed validation by boot services if OVERRIDE_SECURITY_POLICY is set. I am not at computer and would need to double check, but I am pretty sure these would validate any efi verified using shim lock as well. (So this, at least, would seem to be another supported feature of MOK certs?)

On your other point, or one of them, we are not planning to try to get this signed by M$, so I suppose I am implicitly asking for usable support for own-builds of shim (to package up useful functionality which advanced users might want, for themselves) - I appreciate this might remain an unsupported scenario.

**Comment by kukrimate** [comment]
@mikebeaton I appreciate that `OVERRIDE_SECURITY_POLICY` works on your machine and allows loading MOK signed PEs. However this is because your UEFI uses the protocol it installs, not because this is standard functionality. You will be able to do the same thing after shim hooks `LoadImage`, `UnloadImage`, and `StartImage` without `OVERRIDE_SECURITY_POLICY` (I believe this is planned for the next major revision of shim).

For now the best practice is to use the shim lock protocol to verify, then use your own image loader to load images. (As a side note, if GPLv3 is a good license for your use case, you could likely adopt the [PE loader used in Debian](https://salsa.debian.org/grub-team/grub/-/blob/master/debian/patches/secure-boot/efi-use-peimage-shim.patch?ref_type=heads) without too much trouble for your boot loader). Or you can obviously keep using `OVERRIDE_SECURITY_POLICY` but bear in mind it might get removed.

**Comment by mikebeaton** [comment]
Hi - Many thanks for your feedback.

As you are no doubt aware, and were summarising briefly, it's not exactly correct that `OVERRIDE_SECURITY_POLICY` installs a protocol. It [hooks into existing protocols](OVERRIDE_SECURITY_POLICY ), if they are present. The protocols themselves `EFI_SECURITY_ARCH_PROTOCOL` and `EFI_SECURITY2_ARCH_PROTOCOL` very much are [standard](https://uefi.org/sites/default/files/resources/UEFI_PI_Spec_1_8_March3.pdf). I would have to agree, it is less clear to me whether hooking these is in any way supported, or even whether these protocols have to affect `LoadImage` in the way that they apparently do when present. (Or whether this is just a specificity of the EDK-II implementation from which very many brands of firmware inherit.)

Thanks for the suggestion of a loader; our project already has one, in fact with additional security, plus an own format loader.

In terms of how `OVERRIDE_SECURITY_POLICY` currently works, and whether it has any advantages, then it seems to me that the advantages are:
 - All drivers loaded are potentially visible to the original firmware loader (therefore to TPM measurement, etc.) automatically
 - Any other solution requires multiple implementations of loader and measurement

I would agree that if shim hooks `LoadImage` (and `UnloadImage` and `StartImage`) then this is preferable: not every bootloader has to implement its own loader too. I wonder what will be supported by this new initiative, out of what is currently supported by OVERRIDE_SECURITY_POLICY and (in a different way) by shim lock protocol):
 - SBAT enforcement
 - Verification of EFI drivers by Machine Owner Keys (MOK)
 - Ability to verify against and db and dbx signed into (or otherwise loaded into? cf https://github.com/rhboot/shim/issues/521) shim
   - Noting that a non-grub bootloader may wish to load multiple support drivers, before loading one of several different distros, this does still seems convenient and useful to me, although certainly the user _could_ put these into firmware db and dbx, if they had to

**Comment by jsetje** [comment]
@bryteise would you be willing to share the use case that caused you to fix this?

**Comment by bryteise** [comment]
I'll preface this by saying it has been awhile and I wasn't the person who did all of this work originally. Clear Linux builds the [shim](https://github.com/clearlinux-pkgs/shim/blob/main/shim.spec), uses systemd-boot as the efi bootloader and our goal is to support self signing, signing using the microsoft key (not currently being used however) and an internal to Intel signing process (also not currently used).

**Comment by jsetje** [comment]
Thank you! The fact that this shows up Clear Linux doesn't make me any less confused. Although it certainly looks like it was in that spec file for a very long time now. I wonder if anything would brake if it was removed.

FWIW I'm trying to figure out if we should fix the build breakage or rip this out entirely.

**Comment by bryteise** [comment]
I'll see if anybody remembers the original reason for the need to have the option (or a document) but given it is 7 years old I don't expect too much detail if any. My expectation is that the original developer read the code, figured out the path for getting the required behavior at the time and enabled the option to do so. Given we do not currently use 2 of the signing processes we originally designed the configuration around (and I believe self signing is already very robustly supported) I don't think our use case is of much practical importance.

**Comment by joeyli** [comment]
As I remember that the OVERRIDE_SECURITY_POLICY is a callback for grub2 to verify Linux kernel by MOK or shim embedded key. After shim provides shim_lock protocol to grub2, the OVERRIDE_SECURITY_POLICY hacking approach is useless.

I agree that the OVERRIDE_SECURITY_POLICY and relates code can be removed.

**Comment by mikebeaton** [comment]
> As I remember that the OVERRIDE_SECURITY_POLICY is a extra check for grub2 uses load image to verify Linux kernel by MOK or shim embedded key. After shim provides shim_lock protocol to grub2, the OVERRIDE_SECURITY_POLICY hacking approach is useless.
> 
> I agree that the OVERRIDE_SECURITY_POLICY and relates code can be removed.

Why is it hacking? As I mentioned above https://github.com/rhboot/shim/issues/596#issuecomment-1908352329 it seems that it is to spec that the security policy protocol behaves as expected by the OVERRIDE_SECURITY_POLICY code. It hopefully can't be argued that merely overriding protocols is hacky in itself, or at least not unnaceptably so, since shim [does so](https://github.com/rhboot/shim/blob/main/replacements.c#L174) anyway.

The use-case for OVERRIDE_SECURITY_POLICY is for a non-participating bootloader, which potentially loads multiple drivers*, and which wants integration with MOK (for potential driver verification) (this is just a nice-to-have) and SBAT (there is no other way to get it other than going via shim). It seems desirable to avoid a proliferation of loaders, as [each has different behaviour from the others](https://github.com/rhboot/shim/issues/561) (one example of I am quite sure many), and presumably just exapands the attack surface.

*I work on [one](https://github.com/acidanthera/OpenCorePkg), which amongst other features is capable of cleanly booting most standard Linux distros (with or without blspec) directly, without chaining grub. We do have our own [secure image loader](https://github.com/acidanthera/audk/tree/master/MdePkg/Library/BasePeCoffLib2) (actually with additional security features, hence sometimes pop up pointing out [not-to-spec](https://github.com/rhboot/shim/issues/561) [issues](https://lore.kernel.org/linux-efi/CAHzAAWQ6srV6LVNdmfbJhOwhBw5ZzxxZZ07aHt9oKkfYAdvuQQ@mail.gmail.com/T/#u) in the Linux UEFI world). So the issue is not that we don't want to or can't write our own image loader - nor that we couldn't integrate it with shim protocol, if we had to. I guess the issue is really that, going forwards, the only way to get SBAT is via shim, and then, if OVERRIDE_SECURITY_POLICY is removed, the only way to use that is to implement support for shim protocol - which I believe is a shame, even if OVERRIDE_SECURITY_POLICY remains optional and a non-default build mode of shim.

**Comment by mikebeaton** [comment]
Hmmm... after a little further internal discussion... and assuming that OVERRIDE_SECURITY_POLICY is never going to become the way shim works by default (shame! but I guess that ship has long since sailed, and perhaps not relying on OVERRIDE_SECURITY_POLICY allows shim to work on more, and more buggy, types of firmware?) then perhaps our best bet is indeed to add our own SBAT support to our loader...
